apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-vote-app-deploy
  namespace: flask-vote-app
  labels:
    name: flask-vote-app-deploy
    app: flask-vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-vote-app-deploy
      app: flask-vote-app
  template:
    metadata:
      name: flask-vote-app
      labels:
        name: flask-vote-app-deploy
        app: flask-vote-app
    spec:
      containers:
        - name: flask-vote-app
          image: chaitannyaa/flask-vote-app:k8s
          ports:
            - containerPort: 5000
              name: flask-vote-app
          env:
            - name: MYSQL_HOST
              value: mysql-container
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: votes
          spec:
            clusterIP: None
