apiVersion: v1
kind: Service
metadata:
  name: flask-vote-app-service
  namespace: flask-vote-app
  labels:
    app: flask-vote-app
spec:
  selector:
    app: flask-vote-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
