apiVersion: v1
kind: Service
metadata:
  name: flask-vote-app-service
  labels:
    app: flask-vote-app
spec:
  type: LoadBalancer
  selector:
    app: flask-vote-app
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
