apiVersion: v1
kind: Service
metadata:
  name: flask-vote-app-service
  labels:
    name: flask-vote-app-service
    app: flask-vote-app
spec:
  type: NodePort
  selector:
    name: flask-vote-app-deploy
    app: flask-vote-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30430
