apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: flask-vote-app
  labels:
    name: mysql-deployment
    app: flask-vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-container
      app: flask-vote-app
  template:
    metadata:
      name: mysql-container
      labels:
        name: mysql-container
        app: flask-vote-app
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database
          ports:
            - containerPort: 3306
              name: mysql-container
