apiVersion: v1
kind: Service
metadata:
  name: mysql-container
  namespace: flask-vote-app
  labels:
    name: flask-vote-app-service
    app: mysql-app
spec:
  selector:
      name: mysql-app
      app: flask-vote-app
  ports:
    - port: 3306
      targetPort: 3306

