apiVersion: v1
kind: Service
metadata:
  name: flask-vote-app-service
spec:
  selector:
    app: flask-vote-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000